name: CI- Continuous Integration

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the $default-branch 
  push:
    branches: ci/7/setup

  pull_request:
    branches: main

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
         - uses:actions/checkout@v4
         - name: Set up Miniconda
         - uses: conda-incubator/setup-miniconda@v2
           with: 
               installer-url: https://github.com/conda-forge/miniforge/releases/download/4.8.3-2/Miniforge-pypy3-4.8.3-2-Linux-x86_64.sh
               environment-file: env.yml
               auto-update-conda : true
               pyhton-version: '3.12'
        - name: Install dependencies
          run: |
               conda env update --file env.yml
        - name: Run flake8
          run: |
               conda run -n mle-dev flake8
        - name: Run nonstandardcode.py
          run: |
               conda run -n mle-dev python nonstandardcode.py



