name: CI- Continuous Integration
on:
    # Triggers the workflow on push or pull request events but only for the $default-branch 
  push:
    branches: ci/7

  pull_request:
    branches: main

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with: 
        installer-url: https://github.com/conda-forge/miniforge/releases/download/4.8.3-2/Miniforge-pypy3-4.8.3-2-Linux-x86_64.sh
        environment-file: env.yml
        auto-update-conda : true
        pyhton-version: '3.12'
    - name: Install dependencies
      run: |
        conda init
        conda env update --file env.yml
        conda activate mle-dev
    - name: Run flake8
      run: |
        conda install flake8
        flake8 .
    - name: Run nonstandardcode.py
      run: |
        python nonstandardcode.py





         